const orange = [
    {
        "pos":"1",
       "player": {
            "name": "Virat Kohli",
            "team": "RCB",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Virat%20Kohli.png?v=1"
        },
    "runs": "741",
    "MAT":"15",
    "INNS": "15",
    "NO": "3",
    "HS": "113*",
    "AVG": "61.75",
    "BF": "479",
    "SR": "154.69",
    "HUN": "1",
    "FIF": "5",
    "FOURS": "62",
    "SIXES": "38",
},
{
    "pos":"2",
   "player": {
            "name": "Ruturaj Gaikwad",
            "team": "CSK",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Ruturaj%20Gaikwad.png?v=1"
        },
"runs": "583",
"MAT":"14",
"INNS": "14",
"NO": "3",
"HS": "108*",
"AVG": "53.00",
"BF": "413",
"SR": "141.06",
"HUN": "1",
"FIF": "4",
"FOURS": "58",
"SIXES": "18",
},
{
    "pos":"3",
  "player": {
            "name": "Riyan Parag",
            "team": "RR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Riyan%20Parag.png?v=1"
        },
"runs": "573",
"MAT":"16",
"INNS": "14",
"NO": "3",
"HS": "84*",
"AVG": "52.09",
"BF": "384",
"SR": "144.69",
"HUN": "0",
"FIF": "4",
"FOURS": "40",
"SIXES": "33",
},
{
    "pos":"4",
   "player": {
            "name": "Travis Head",
            "team": "SRH",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Travis%20Head.png?v=1"
        },
"runs": "567",
"MAT":"15",
"INNS": "15",
"NO": "1",
"HS": "102",
"AVG": "40.75",
"BF": "296",
"SR": "191.69",
"HUN": "1",
"FIF": "4",
"FOURS": "62",
"SIXES": "32",
},
{
    "pos":"5",
   "player": {
            "name": "Sanju Samson",
            "team": "RR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Sanju%20Samson.png?v=1"
        },
"runs": "531",
"MAT":"16",
"INNS": "15",
"NO": "4",
"HS": "86",
"AVG": "48.75",
"BF": "346",
"SR": "154.69",
"HUN": "0",
"FIF": "3",
"FOURS": "42",
"SIXES": "28",
},
{
    "pos":"6",
   "player": {
            "name": "Sai Sudharsan",
            "team": "GT",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Sai%20Sudharsan.png?v=1"
        },
"runs": "527",
"MAT":"12",
"INNS": "12",
"NO": "1",
"HS": "103",
"AVG": "41.75",
"BF": "379",
"SR": "134.69",
"HUN": "1",
"FIF": "5",
"FOURS": "42",
"SIXES": "28",
},
{
    "pos":"7",
   "player": {
            "name": "KL Rahul",
            "team": "LSG",
            "picture": "https://scores.iplt20.com/ipl/playerimages/K%20L%20Rahul.png?v=1"
        },
"runs": "520",
"MAT":"14",
"INNS": "14",
"NO": "0",
"HS": "82",
"AVG": "37.75",
"BF": "382",
"SR": "136.69",
"HUN": "0",
"FIF": "4",
"FOURS": "45",
"SIXES": "19",
},
{
    "pos":"8",
   "player": {
            "name": "Nicholas Pooran",
            "team": "LSG",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Nicholas%20Pooran.png?v=1"
        },
"runs": "499",
"MAT":"14",
"INNS": "14",
"NO": "0",
"HS": "109",
"AVG": "34.86",
"BF": "270",
"SR": "180.29",
"HUN": "1",
"FIF": "3",
"FOURS": "50",
"SIXES": "33",
},
{
    "pos":"9",
   "player": {
            "name": "Sunil Narine",
            "team": "KKR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Sunil%20Narine.png?v=1"
        },
"runs": "488",
"MAT":"15",
"INNS": "14",
"NO": "0",
"HS": "109",
"AVG": "34.71",
"BF": "270",
"SR": "180.69",
"HUN": "1",
"FIF": "3",
"FOURS": "50",
"SIXES": "33",
},
{
    "pos":"10",
   "player": {
            "name": "Abhishek Sharma",
            "team": "SRH",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Abhishek%20Sharma.png?v=1"
        },
"runs": "484",
"MAT":"16",
"INNS": "16",
"NO": "1",
"HS": "75",
"AVG": "32.27",
"BF": "237",
"SR": "204.69",
"HUN": "0",
"FIF": "3",
"FOURS": "36",
"SIXES": "42",
},
{
    "pos":"11",
  "player": {
            "name": "Heinrich Klaasen",
            "team": "SRH",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Heinrich%20Klaasen.png?v=1"
        },
"runs": "479",
"MAT":"16",
"INNS": "15",
"NO": "3",
"HS": "80*",
"AVG": "39.75",
"BF": "280",
"SR": "171.69",
"HUN": "0",
"FIF": "4",
"FOURS": "19",
"SIXES": "38",
},
{
    "pos":"12",
   "player": {
            "name": "Rishabh Pant",
            "team": "DC",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Rishabh%20Pant.png?v=1"
        },
"runs": "446",
"MAT":"13",
"INNS": "13",
"NO": "2",
"HS": "88*",
"AVG": "40.00",
"BF": "287",
"SR": "157.69",
"HUN": "0",
"FIF": "3",
"FOURS": "36",
"SIXES": "25",
},
{
    "pos":"13",
   "player": {
            "name": "Faf du Plessis",
            "team": "RCB",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Faf%20Du%20Plessis.png?v=1"
        },
"runs": "438",
"MAT":"15",
"INNS": "15",
"NO": "0",
"HS": "64",
"AVG": "29.75",
"BF": "271",
"SR": "161.62",
"HUN": "0",
"FIF": "4",
"FOURS": "47",
"SIXES": "21",
},
{
    "pos":"14",
  "player": {
            "name": "Phil Salt",
            "team": "KKR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Phil%20Salt.png?v=1"
        },
"runs": "435",
"MAT":"12",
"INNS": "12",
"NO": "1",
"HS": "89*",
"AVG": "39.55",
"BF": "239",
"SR": "182.69",
"HUN": "0",
"FIF": "4",
"FOURS": "50",
"SIXES": "24",
},
{
    "pos":"15",
   "player": {
            "name": "Yeshasvi Jaiswal",
            "team": "RR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Yashasvi%20Jaiswal.png?v=1"
        },
"runs": "435",
"MAT":"16",
"INNS": "15",
"NO": "1",
"HS": "104*",
"AVG": "31.75",
"BF": "277",
"SR": "155.69",
"HUN": "1",
"FIF": "1",
"FOURS": "54",
"SIXES": "16",
},
{
    "pos":"16",
   "player": {
            "name": "Shubman Gill",
            "team": "GT",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Shubman%20Gill.png?v=1"
        },
"runs": "426",
"MAT":"12",
"INNS": "12",
"NO": "1",
"HS": "104",
"AVG": "38.75",
"BF": "289",
"SR": "147.69",
"HUN": "1",
"FIF": "2",
"FOURS": "37",
"SIXES": "15",
},
{
    "pos":"17",
  "player": {
            "name": "Rohit Sharma",
            "team": "MI",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Rohit%20Sharma.png?v=1"
        },
"runs": "417",
"MAT":"14",
"INNS": "14",
"NO": "1",
"HS": "105*",
"AVG": "32.08",
"BF": "267",
"SR": "150.69",
"HUN": "1",
"FIF": "1",
"FOURS": "45",
"SIXES": "23",
},
{
    "pos":"18",
  "player": {
            "name": "Tilak Varma",
            "team": "MI",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Tilak%20Varma.png?v=1"
        },
"runs": "416",
"MAT":"13",
"INNS": "13",
"NO": "3",
"HS": "65",
"AVG": "41.60",
"BF": "278",
"SR": "149.64",
"HUN": "0",
"FIF": "3",
"FOURS": "35",
"SIXES": "19",
},
{
    "pos":"19",
   "player": {
            "name": "Shivam Dube",
            "team": "CSK",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Shivam%20Dube.png?v=1"
        },
"runs": "396",
"MAT":"14",
"INNS": "14",
"NO": "3",
"HS": "66*",
"AVG": "36.75",
"BF": "244",
"SR": "162.69",
"HUN": "0",
"FIF": "3",
"FOURS": "28",
"SIXES": "28",
},
{
    "pos":"20",
   "player": {
            "name": "Rajat Patidar",
            "team": "RCB",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Rajat%20Patidar.png?v=1"
        },
"runs": "395",
"MAT":"15",
"INNS": "13",
"NO": "0",
"HS": "55",
"AVG": "30.38",
"BF": "223",
"SR": "177.13",
"HUN": "0",
"FIF": "5",
"FOURS": "21",
"SIXES": "33",
},
]