const orange = [
    {
        "pos":"1",
       "player": {
            "name": "Harshal Patel",
            "team": "PBKS",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Harshal%20Patel.png?v=1"
        },
    "WKTS": "24",
    "MAT":"14",
    "INNS": "14",
    "OV": "49",
    "RUNS": "477",
    "BBI": "15/3",
    "AVG": "19.87",
    "ECON": "9.73",
    "SR": "12.25",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"2",
       "player": {
            "name": "Varun Chakravarthy",
            "team": "KKR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Varun%20Chakaravarthy.png?v=1"
        },
    "WKTS": "21",
    "MAT":"15",
    "INNS": "14",
    "OV": "50",
    "RUNS": "402",
    "BBI": "16/3",
    "AVG": "19.14",
    "ECON": "8.04",
    "SR": "14.28",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"3",
       "player": {
            "name": "Jasprit Bumrah",
            "team": "MI",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Jasprit%20Bumrah.png?v=1"
        },
    "WKTS": "20",
    "MAT":"13",
    "INNS": "13",
    "OV": "51.5",
    "RUNS": "336",
    "BBI": "21/5",
    "AVG": "16.80",
    "ECON": "6.48",
    "SR": "15.55",
    "FOW": "0",
    "FW": "1",
},
    {
        "pos":"4",
       "player": {
            "name": "T Natarajan",
            "team": "SRH",
            "picture": "https://scores.iplt20.com/ipl/playerimages/T%20Natarajan.png?v=1"
        },
    "WKTS": "19",
    "MAT":"14",
    "INNS": "14",
    "OV": "51.2",
    "RUNS": "465",
    "BBI": "19/4",
    "AVG": "24.47",
    "ECON": "9.05",
    "SR": "16.21",
    "FOW": "1",
    "FW": "0",
},
    {
        "pos":"5",
       "player": {
            "name": "Harshit Rana",
            "team": "KKR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Harshit%20Rana.png?v=1"
        },
    "WKTS": "19",
    "MAT":"13",
    "INNS": "11",
    "OV": "42.1",
    "RUNS": "383",
    "BBI": "24/3",
    "AVG": "20.15",
    "ECON": "9.08",
    "SR": "13.31",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"6",
       "player": {
            "name": "Avesh Khan",
            "team": "RR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Avesh%20Khan.png?v=1"
        },
    "WKTS": "19",
    "MAT":"16",
    "INNS": "15",
    "OV": "54.5",
    "RUNS": "526",
    "BBI": "27/3",
    "AVG": "27.68",
    "ECON": "9.59",
    "SR": "17.31",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"7",
       "player": {
            "name": "Arshdeep Singh",
            "team": "PBKS",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Arshdeep%20Singh.png?v=1"
        },
    "WKTS": "19",
    "MAT":"14",
    "INNS": "14",
    "OV": "50.2",
    "RUNS": "505",
    "BBI": "29/4",
    "AVG": "26.57",
    "ECON": "10.03",
    "SR": "15.89",
    "FOW": "1",
    "FW": "0",
},
    {
        "pos":"8",
       "player": {
            "name": "Andre Russell",
            "team": "KKR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Andre%20Russell.png?v=1"
        },
    "WKTS": "19",
    "MAT":"15",
    "INNS": "14",
    "OV": "29.2",
    "RUNS": "295",
    "BBI": "19/3",
    "AVG": "15.52",
    "ECON": "10.05",
    "SR": "9.26",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"9",
       "player": {
            "name": "Pat Cummins",
            "team": "SRH",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Pat%20Cummins.png?v=1"
        },
    "WKTS": "18",
    "MAT":"16",
    "INNS": "16",
    "OV": "61.0",
    "RUNS": "566",
    "BBI": "43/3",
    "AVG": "31.44",
    "ECON": "9.27",
    "SR": "20.33",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"10",
       "player": {
            "name": "Yuzvendra Chahal",
            "team": "RR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Yuzvendra%20Chahal.png?v=1"
        },
    "WKTS": "18",
    "MAT":"15",
    "INNS": "15",
    "OV": "58.0",
    "RUNS": "546",
    "BBI": "11/3",
    "AVG": "30.33",
    "ECON": "9.41",
    "SR": "19.33",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"11",
       "player": {
            "name": "Sunil Narine",
            "team": "KKR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Sunil%20Narine.png?v=1"
        },
    "WKTS": "17",
    "MAT":"15",
    "INNS": "14",
    "OV": "55",
    "RUNS": "368",
    "BBI": "22/2",
    "AVG": "21.64",
    "ECON": "6.69",
    "SR": "19.41",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"12",
       "player": {
            "name": "Tushar Deshpande",
            "team": "CSK",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Tushar%20Deshpande.png?v=1"
        },
    "WKTS": "17",
    "MAT":"13",
    "INNS": "13",
    "OV": "48",
    "RUNS": "424",
    "BBI": "27/4",
    "AVG": "24.94",
    "ECON": "10.08",
    "SR": "16.94",
    "FOW": "1",
    "FW": "0",
},
    {
        "pos":"13",
       "player": {
            "name": "Khaleel Ahmed",
            "team": "DC",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Khaleel%20Ahmed.png?v=1"
        },
    "WKTS": "17",
    "MAT":"14",
    "INNS": "14",
    "OV": "50.0",
    "RUNS": "479",
    "BBI": "21/2",
    "AVG": "28.18",
    "ECON": "9.58",
    "SR": "17.64",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"14",
       "player": {
            "name": "Mukesk Kumar",
            "team": "DC",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Mukesh%20Kumar.png?v=1"
        },
    "WKTS": "17",
    "MAT":"10",
    "INNS": "10",
    "OV": "35.5",
    "RUNS": "368",
    "BBI": "14/3",
    "AVG": "21.64",
    "ECON": "10.26",
    "SR": "12.65",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"15",
       "player": {
            "name": "Mitchell Starc",
            "team": "KKR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Mitchell%20Starc.png?v=1"
        },
    "WKTS": "17",
    "MAT":"14",
    "INNS": "13",
    "OV": "41.5",
    "RUNS": "444",
    "BBI": "33/4",
    "AVG": "26.12",
    "ECON": "10.59",
    "SR": "14.76",
    "FOW": "1",
    "FW": "0",
},
    {
        "pos":"16",
       "player": {
            "name": "Trent Boult",
            "team": "RR",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Trent%20Boult.png?v=1"
        },
    "WKTS": "16",
    "MAT":"16",
    "INNS": "15",
    "OV": "53.2",
    "RUNS": "443",
    "BBI": "22/3",
    "AVG": "27.68",
    "ECON": "8.30",
    "SR": "20.00",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"17",
       "player": {
            "name": "Kuldeep Yadav",
            "team": "DC",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Kuldeep%20Yadav.png?v=1"
        },
    "WKTS": "16",
    "MAT":"11",
    "INNS": "11",
    "OV": "43.0",
    "RUNS": "374",
    "BBI": "55/4",
    "AVG": "23.37",
    "ECON": "8.69",
    "SR": "16.12",
    "FOW": "1",
    "FW": "0",
},
    {
        "pos":"18",
       "player": {
            "name": "Sam Curran",
            "team": "PBKS",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Sam%20Curran.png?v=1"
        },
    "WKTS": "16",
    "MAT":"13",
    "INNS": "13",
    "OV": "41.0",
    "RUNS": "416",
    "BBI": "28/3",
    "AVG": "26.00",
    "ECON": "10.14",
    "SR": "15.37",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"19",
       "player": {
            "name": "Yash Dayal",
            "team": "RCB",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Yash%20Dayal.png?v=1"
        },
    "WKTS": "15",
    "MAT":"14",
    "INNS": "14",
    "OV": "50.1",
    "RUNS": "459",
    "BBI": "20/3",
    "AVG": "30.60",
    "ECON": "9.14",
    "SR": "20.07",
    "FOW": "0",
    "FW": "0",
},
    {
        "pos":"20",
       "player": {
            "name": "Mohammed Siraj",
            "team": "RCB",
            "picture": "https://scores.iplt20.com/ipl/playerimages/Mohammed%20Siraj.png?v=1"
        },
    "WKTS": "15",
    "MAT":"14",
    "INNS": "14",
    "OV": "54.0",
    "RUNS": "496",
    "BBI": "43/3",
    "AVG": "33.07",
    "ECON": "9.18",
    "SR": "21.60",
    "FOW": "0",
    "FW": "0",
},
]